version: "3"

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: autoparts_service_db
    volumes:
      - db:/data/db/

volumes:
  db: