version: "3"

services:

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: autoparts-back:0.1.0
    environment:
      DB_URL: mongodb://mongo
    ports:
      - "8081:8081"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: autoparts_service_db
    volumes:
      - db:/data/db/

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: autoparts-front:0.1.0
    environment:
      VITE_APP_API_ROOT_URL: http://localhost:8081
    ports:
      - "8080:80"

volumes:
  db: