name: Mongo Service Example

on: push

jobs:
  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest
    env:
      TTL_IMAGE_NAME: autoparts_db
      TTL_IMAGE_DURATION: 1h

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      mongo:
        # Docker Hub image
        image: mongo:4.4
       
        env:
          MONGO_INITDB_USERNAME: $MONGO_ROOT_USERNAME
          MONGO_INITDB_PASSWORD: $MONGO_ROOT_PASSWORD
          MONGO_INITDB_DATABASE: autoparts_service_db
        
        volumes:
          - db:/data/db/
        ports:
          # Maps tcp port 5432 on service container to the host
          - 27017:27017

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: "Build image tag from env"
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          IMAGE_TAG=ttl.sh/${{ env.TTL_IMAGE_NAME }}:${{ env.TTL_IMAGE_DURATION }}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: "Build docker image ${{ env.IMAGE_TAG }}"
        run: |
          docker build -t ${{ env.IMAGE_TAG }} ./backend/

      - name: "Push docker image ${{ env.IMAGE_TAG }}"
        run: |
          docker push ${IMAGE_TAG}